/*`timescale 1ns/1ps

// Receives the 7-bit symbols generated by symbol_mapper.
//
// 64-bit frame -> ceil(64/7) = 10 symbols.
// 10 symbols = 70 bits, so the mapper adds 6 zero padding bits.
//
// Frame:
// [63:56] SOF  = A5
// [55: 8] Packet (48 bits)
// [ 7: 0] EOF  = 5A

module packet_decoder (
    input  logic clk,
    input  logic rst,

    input  logic [6:0] symbol_in,
    input  logic       symbol_valid,

    output logic [47:0] packet_out,
    output logic        packet_valid
);

    localparam int NUM_SYMBOLS = 10;

    logic [69:0] buffer;
    logic [3:0]  symbol_count;
    logic [63:0] frame_received;

    always_ff @(posedge clk) begin
        if (rst) begin
            buffer         <= 70'd0;
            symbol_count   <= 4'd0;
            frame_received <= 64'd0;
            packet_out     <= 48'd0;
            packet_valid   <= 1'b0;
        end else begin
            packet_valid <= 1'b0;

            if (symbol_valid) begin
                buffer <= {buffer[62:0], symbol_in};

                if (symbol_count == NUM_SYMBOLS-1) begin
                    frame_received <= {buffer[62:0], symbol_in}[63:0];

                    if (({buffer[62:0], symbol_in}[63:56] == 8'hA5) &&
                        ({buffer[62:0], symbol_in}[7:0]   == 8'h5A)) begin
                        packet_out   <= {buffer[62:0], symbol_in}[55:8];
                        packet_valid <= 1'b1;
                    end

                    symbol_count <= 4'd0;
                end else begin
                    symbol_count <= symbol_count + 1'b1;
                end
            end
        end
    end

endmodule
*/

`timescale 1ns/1ps
module dechirper(input logic clk,input logic rst,input logic signed [15:0] i_in,input logic signed [15:0] q_in,input logic valid_in,output logic signed [15:0] i_out,output logic signed [15:0] q_out,output logic valid_out);
    always_ff @(posedge clk) begin if(rst) begin i_out<=0;q_out<=0;valid_out<=0; end else begin i_out<=i_in;q_out<=q_in;valid_out<=valid_in; end end
endmodule

